[project]
name = "hello-sagemaker"
version = "0.1.0"
description = "Sagemaker Hello World"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebook>=7.3.3",
    "pandas>=2.2.3",
]
